version: "3"

services: 
  api:
    container_name: iosWebServer
    restart: always
    build: .
    command: npm run dev
    ports:
      - "4000:4000"
    links: 
      - database
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    container_name: mongoDB_IOS
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
    volumes:
      - ./db/data:/data/db
      - ./home:/home
